esphome:
  name: dcwifiswitch
  friendly_name: DCWiFiSwitch

esp8266:
  board: esp01_1m

# Enable logging
logger:

captive_portal:

switch:
  - platform: gpio
    id: output_1
    pin: GPIO12
    name: "Output1"
  - platform: gpio
    id: output_2
    pin: GPIO14
    name: "Output2"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      inverted: true
    name: Button
    filters:
      - delayed_on_off: 20ms
    on_press:
      then:
        - switch.toggle: output_1

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s